mybatis:
  type-aliases-package: com.mdzn.via.domain
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


devtools:
  livereload:
    enabled: true # 서버를 재시작하지 않아도 resources 폴더의 변경 사항이 바로 반영
  restart:
    enabled: true # 서버를 재시작하지 않아도 .java 파일의 변경사항 반영